name: "[feat]: 기능 제안"
description: 새로운 기능을 추가하거나 기존의 기능을 수정할 때 사용하는 이슈 템플릿
title: "[feat]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        양식에 맞춰 이슈를 생성한 다음 [feat/이슈번호(숫자만)-브랜치이름]으로 브랜치를 생성해서 개발해주세요.
        (이슈번호가 #24일때 브랜치 이름 예시: feat/24-STT)

        하나의 이슈에 여러 기능을 추가하는 것보다, 이슈를 여러개 나눠 빠른 개발과 코드 업데이트가 이루어지도록 해주세요.
        
        개발이 완료되면 Pull requests 후 팀장에게 리뷰 요청해주세요.
        리뷰가 완료되면 직접 merge 하시면 됩니다. 단, merge 충돌 발생시 진행하지 말고 반드시 말씀해주세요.
        
  - type: textarea
    id: details
    attributes:
      label: 개발 내용
      description: 추가하거나 수정할 기능을 설명해주세요
      placeholder: 개조식으로, 줄표(-) 목록으로 작성해주세요
    validations:
      required: true

  - type: textarea
    id: etc
    attributes:
      label: 기타
      description: 기타 참고사항이 있으면 적어주세요
      placeholder: 개조식으로, 줄표(-) 목록으로 작성해주세요
    validations:
      required: False
      
