name: "버그 제보"
description: 코드 상에 버그가 발생하였을 때 제보 이슈 템플릿
title: "[bug]: "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        양식에 맞춰 이슈를 생성한 다음 [fix/이슈번호(숫자만)-브랜치이름]으로 브랜치를 생성해서 개발해주세요.
        (이슈번호가 #24일때 브랜치 이름 예시: fix/24-STT)

  - type: textarea
    id: details
    attributes:
      label: 버그 내용
      description: 발생한 버그 내용을 설명해주세요
      placeholder: 개조식으로 작성해주세요
      value: |
        - 내용 1 (개조식으로 작성)
        - 내용 2
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: 오류 로그
      description: 발생한 오류 로그를 그대로 여기에 붙여넣어주세요.
      placeholder: 발생한 오류 로그를 그대로 여기에 붙여넣어주세요.
      render: shell
    validations:
      required: False

  - type: textarea
    id: etc
    attributes:
      label: 기타
      description: 기타 참고사항이 있으면 적어주세요
      placeholder: 개조식으로 작성해주세요
    validations:
      required: False

  - type: markdown
    attributes:
      value: |
        개발이 완료되면 Pull requests 후 팀장에게 리뷰 요청해주세요.
        리뷰가 완료되면 직접 merge 하시면 됩니다. 단, merge 충돌 발생시 진행하지 말고 반드시 말씀해주세요.
        
